name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:

    uses: zhjpwlj/ultimate-deploy-system/.github/workflows/workflow.yml@v2.0.0

    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
